# Generated by Django 4.2.1 on 2023-05-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_aiproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproject',
            name='image',
            field=models.FilePathField(path='C:\\Users\\TBO\\Coding\\Projects\\Personal Projects\\Portfolio_Website\\img/AI'),
        ),
    ]
